# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
postgresql: &postgresql
  adapter: postgresql
  pool: 5
  timeout: 5000
  
development:
  <<: *postgresql
  database: srenvio_development

  username: "postgres"
  password: "123"

test:
  <<: *postgresql
  database: srenvio_test

production:
  <<: *postgresql
  database: srenvio_production
